### PR TITLE
Fix English grammar in src/WORKSPACE.bazel

### PR DESCRIPTION
**Pull request by akihikodaki**

### CODE REVIEW

**Comment by hiroyuki-komatsu** [comment]
Thanks.

**Comment by Arfrever** [comment]
@hiroyuki-komatsu
You accidentally reverted this change in commit 081179512cf229c90903ef07bd409b77ea258a3b.

**Comment by Arfrever** [comment]
So there was forced push which replaced commit 081179512cf229c90903ef07bd409b77ea258a3b with commit e1a479ed605c5b3c7798a76d5f5abb0964894a16, and dropped commit 0f6ccf319353bb7278d2510691ff2d8e788dbd27...

**Comment by hiroyuki-komatsu** [comment]
I am sorry about the inconvenience. We had to do the force push to revert several unintended commits.

The replacement of https://github.com/google/mozc/commit/081179512cf229c90903ef07bd409b77ea258a3b was a by-product.

**Pull request merged**
