### PR TITLE
To reduce the version differences of modules between WORKSPACE.bazel and MODULE.bazel.

### PR DESCRIPTION
**Pull request by phoepsilonix**
## Description
There were version differences in external dependency modules when building with the options --noenable_bzlmod (--config workspace) and enable_bzlmod, so we reduced these differences.
Additionally, by separating the Bazel files for qt_macos, we encouraged a decrease in analysis time　during builds on Linux and other platforms.

## Additional context
When specifying --noenable_bzlmod, the build completes even without network access. However, the versions of the required modules are slightly different.

I encountered an issue where I couldn't build without network access due to differences in Bazel versions and switching between enabling and disabling bzlmod. So, I made some adjustments.

When bzlmod is enabled, it seems that remote patches and some modules need to be downloaded. Since bzlmod is enabled by default, network access is essentially required.

```
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> protobuf@_ -> rules_pkg@0.7.0: Error accessing registry https://bcr.bazel.build/: Unknown host: bcr.bazel.build
```

While I believe building would be possible if the repository_cache is sent as is, it seems difficult with the distdir option.
If bzlmod is disabled, it was possible to build more easily without network access by specifying the archive files of necessary modules with the distdir option.

Because the module versions differ between bzlmod and workspace (--noenable_bzlmod), this commit is an attempt to adjust them to be as similar as possible.

However, modifying files in this part might not have been accepted due to policy. If that's the case, please feel free to close it.

### CODE REVIEW

**Comment by hiroyuki-komatsu** [comment]
Hi phoepsilonix,
Thank you for your PR.

### offline builds with Bzlmod

For offline builds with Bzlmod, you also need to specify the `--registry` option.

```
bazel fetch --repository_cache="/path/to/repository_cache"
git clone https://github.com/bazelbuild/bazel-central-registry.git /path/to/bcr
bazel build --repository_cache=/path/to/repository_cache --registry=file:///path/to/bcr …
```

If you have additional questions, please feel free to ask it in Discussions.


### build errors on macOS

I got the following errors with your PR on macOS.
Could you please double check whether your PR works for the macOS build?

mozc/src% MOZC_QT_PATH=${PWD}/third_party/qt bazel build --config oss_macos package
```
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_komatsu/16974d89627788468869c7fcdea85b18/external/rules_python~/python/private/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_11' from module 'rules_android': Toolchain 'python_3_11' from module 'rules_python' already registered Python version 3.11 and has precedence
DEBUG: /private/var/tmp/_bazel_komatsu/16974d89627788468869c7fcdea85b18/external/rules_android_ndk~/rules.bzl:28:14: Either the ANDROID_NDK_HOME environment variable or the path attribute of android_ndk_repository must be set.
ERROR: /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel: no such target '//gui/about_dialog:about_dialog_macos': target 'about_dialog_macos' not declared in package 'gui/about_dialog' defined by /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel (did you mean about_dialog_main, or about_dialog_ja.qm?)
ERROR: /Users/komatsu/github/mozc/src/mac/BUILD.bazel:56:23: no such target '//gui/about_dialog:about_dialog_macos': target 'about_dialog_macos' not declared in package 'gui/about_dialog' defined by /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel (did you mean about_dialog_main, or about_dialog_ja.qm?) and referenced by '//mac:mozc_macos'
ERROR: Analysis of target '//:package' failed; build aborted: Analysis failed
INFO: Elapsed time: 74.773s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

mozc/src% MOZC_QT_PATH=${PWD}/third_party/qt bazel build --config oss_macos --noenable_bzlmod package
```
ERROR: /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel: no such target '//gui/about_dialog:about_dialog_macos': target 'about_dialog_macos' not declared in package 'gui/about_dialog' defined by /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel (did you mean about_dialog_main, or about_dialog_ja.qm?)
ERROR: /Users/komatsu/github/mozc/src/mac/BUILD.bazel:56:23: no such target '//gui/about_dialog:about_dialog_macos': target 'about_dialog_macos' not declared in package 'gui/about_dialog' defined by /Users/komatsu/github/mozc/src/gui/about_dialog/BUILD.bazel (did you mean about_dialog_main, or about_dialog_ja.qm?) and referenced by '//mac:mozc_macos'
ERROR: Analysis of target '//:package' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.140s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@local_config_apple_cc; starting
    Fetching repository @@local_config_xcode; Fetching the default Xcode version
```

### WORKSPACE and Bzlmod

Since WORKSPACE and  –distdir will be deprecated and removed from Bazel in future, we'd like to focus on Bzlmod.
Updating versions in WORKSPACE makes sense, but modifying Bzlmod and BUILD files for WORKSPACE is not preferred.

**Comment by phoepsilonix** [comment]
"First of all, thank you very much for your response. I especially appreciate your information about the --registry option, which was very helpful. Some distribution build servers restrict network access during the build process after uploading trusted sources. It seems that building will be possible even in such environments. However, in such environments, if --distdir is deprecated in the future, offline builds might be difficult without manually reconstructing the repository cache. This is because uploading the repository cache as-is would probably not be allowed. In any case, I'm deeply grateful that we were able to clarify the steps to enable offline builds. As for the MAC build environment, I had confirmed up to the point where the toolchain couldn't be found due to the lack of a build environment. If it turns out that the build cannot be completed successfully, it might be better to close it.

**Comment by yukawa** [comment]
> If bzlmod is disabled, it was possible to build more easily without network access by specifying the archive files of necessary modules with the distdir option.

If you find any questions about offline build in bzlmod mode, I’d suggest looking for information in the Bazel community first, since improving offline build support is one of the key goals of bzlmod as [clearly described in its original proposal](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/preview). I am pretty sure that the upstream Bazel team is aware of the use cases you mentioned.
> **Poor support for enterprise use cases**
> * Bazel does not offer an easy way to set up and perform an offline build.
>   * It's possible to use `--distdir` to avoid downloading certain archives, but there is no automatic workflow to set up a distdir. There are also further problems with the distdir setup: it contains unextracted archives; files in the distdir are not distinguished by the full URL; etc.
>   * To enforce a build to be offline, users need to rely on the undocumented `--nofetch` flag, which completely disables repo rule evaluation (even guaranteed offline logic such as extracting distdir archives).
> * There is no good way to force all dependencies to come from an internal server or proxy.
Since each repo rule invocation directly names a list of URLs, users need to change every single invocation to force everything to come from an internal server or proxy.
>   * This is exacerbated by the deps.bzl pattern -- users need to override the URLs of indirect dependencies by hand.
>  * There is no sure-fire way to override a dependency to use a local directory (aka "vendoring").
>    * Mostly due to the prevalence of the `deps.bzl` pattern and the uncertainty of WORKSPACE evaluation order.
>    * There is also no easy way to set up a dependency to be vendored (users have to perform manual downloads).

**Comment by phoepsilonix** [comment]
The files in the folder specified by distdir don't change frequently, right? Repeatedly uploading these could be considered a waste of network resources. For some systems, it might be possible to manage previously uploaded archives using URLs and HASHes, and avoid fetching them again if the same ones are specified. If distdir is deprecated, it would be nice to have a similar functionality with a different option.

>I am pretty sure that the upstream Bazel team is aware of the use cases you mentioned.

Thank you so much.
Please convey my regards.

**Comment by phoepsilonix** [comment]
For now, we'll call it off. If there's another opportunity, I'll try to separate it again.
Thank you very much for checking various things.

**Comment by phoepsilonix** [comment]
P.S.

 I think people would be pleased if there were also release files in bcr.

**Pull request closed without merging**
